%% Read a DICOM file, make some plots and anonymize personal data
% The main steps of this demo are:
% to read a DICOM file;
% to display a 2D image;
% to plot image plofiles, etc.;
% to explore metadata information;
% to anonymize exams.
%
% Sample DICOM images are available at
% <https://pandora.infn.it/public/cmepda/DATASETS/IMAGES/DICOM_Examples/ INFN Pandora>
% or on drive <https://drive.google.com/drive/folders/1YqK7ZkM-P2IrqfD7Pj-SCmjz-GWd_1-Y?usp=sharing Google drive folder>
% 
%% Clear the workspace, close all figures, search for functions to use  
% Before you start a new analysis, clear the workspace and close all
% figures
clear
close all
clc
 
%%
% If you are searching for a function and you do not know its name you can 
% use lookfor

lookfor dicom

% it searches for the specified keyword in the first comment line 
% (the H1 line) of the help text in all MATLAB program files found on 
% the search path. 
% For all files in which a match occurs, lookfor displays the H1 line.
% Tip: put the right keywords in the first comment line of your scripts 
% and functions

%% Read a DICOM file
% Try with a brain MRI slice in the 
% DATASETS/IMAGES/DICOM_Examples/Brain_MRI/ directory
% or try with a mammogram, which is in folder
% DATASETS/IMAGES/DICOM_Examples/Breast_Mammography_Case2/
filename='../DATASETS/IMAGES/DICOM_Examples/Brain_MRI/IM67_1slice.dcm';

%% 
% You can also interactively choose a file to open using the uiget function

% [file,path] = uigetfile('*.dcm','Select a DICOM File');
% filename=strcat(path,file);

%% 
% You can read a DICOM file using the dicomread function
Im=dicomread(filename);

%% 
% Check the size and format of the Im variable in the workspace 
whos Im
%%
size(Im)
%%
[min(Im(:)) max(Im(:)) range(Im(:))]

%% Display a 2D image
imagesc(Im)
colormap(gray)

%% Plot plofiles, etc.
% Plot an image profile of a central image row
x=1:size(Im,2);
L=round(size(Im,1)/2);
y=Im(L,:);
plot(x,y)

%% 
% To reduce the noise, average over 5 close image lines
Im_slab=Im((L-2:L+2),:);
yy=mean(Im_slab); % by default it average over the first array dimension
plot(x,yy);

%% 
% Plot the profiles in the same figure
plot(x,y,'--',x,yy,'-r');
legend('1-row profile',' 5-row average profile')

%%
% Plot in the same figure the image profiles of three image rows
% (one in the upper part, one in the middle and one in the lower part of
% the image)
Lup=round(size(Im,1)/4);
Ldown=round(size(Im,1)*3/4);
yup=mean(Im((Lup-2:Lup+2),:));
ydown=mean(Im((Ldown-2:Ldown+2),:));
figure;
plot(x,yy,x,yup,'r',x,ydown,'k');

%%
% Use subplot to display the image on the left and the three profiles
% one below the other on the right
figure;
subplot(3,2,[1 3 5])
imagesc(Im)
subplot(3,2,2);
plot(x,yup,'r'); title(strcat('profile at row =', num2str(Lup)))
subplot(3,2,4)
plot(x,yy); title(strcat('profile at row =', num2str(L)))
subplot(3,2,6)
plot(x,ydown,'k'); title(strcat('profile at row =', num2str(Ldown)))


%% Explore metadata information
% The dicomdisp function reads and displays all metadata information
dicomdisp(filename)

%%
% Put information in a structure
metadata=dicominfo(filename);

%%
% Display the fields of the structure generated by dicominfo
fieldnames(metadata)

%% 
% You can use the tab after "metadata." to directly explore the fields

%% 
% Some fields contain info about the image acquisition process, e.g.:
metadata.Modality

%% 
% Some fields are modality specific, e.g.

metadata.MagneticFieldStrength  % for MR modality
%metadata.ExposureTime           % exposure time in ms for mammography MG

%%
% Some fields may contain sensitive patients' data --> to be anonymized
metadata.PatientName

%% 
% Some fields contain useful information for data analysis, e.g. those 
% related to the physical size of voxels (they are expressed in mm)
metadata.PixelSpacing
metadata.SliceThickness      % SliceThickness is only available fro 3D modalities

%% 
% If we know the dicom tag and we want to know the field name we can use
% the dicomlookup function
dicomlookup('0010','0020')   % PatientID
dicomlookup('0018', '1314')  % FlipAngle

%% Make a plot of an image profile, with physical units on x axis
x_mm= metadata.PixelSpacing*x;
figure;
plot(x_mm,y,'r');
xlabel('position (mm)')

%% Anonymize the DICOM file 
% First, we define the name of the anonymized file to store
name_s = strsplit(filename,'.dcm');
filename_anon=strcat(name_s{1},'_anonymized.dcm');

%% 
% We use the dicomanon function to anonymize DICOM files
dicomanon(filename,filename_anon);

%%
% We check the metadata of the anonymized file 
metadata_anon=dicominfo(filename_anon);
% to be sure that names and personal data of the subject have been cleared

%% 
% Some fields have been omitted. To find them we can compare the content
% of two different cell arrays with the setdiff() function
fm=fieldnames(metadata);
fm_anon=fieldnames(metadata_anon);
setdiff(fm,fm_anon)

%% 
% Check the documentation of the dicomanon function.
% For example, to select specific fields to keep during
% the anonymization process:
dicomanon(filename,filename_anon, 'keep', {'PatientAge','PatientWeight'});





